class ArAr {
  static const Map<String, String> message = {
    "appName": "التسوق الذكي",
    'hello': 'اهلا',
    'warning': 'تنبيه',
    'yes': 'نعم',
    'cancel': 'الغاء',
    'alertexitingApp': 'هل تريد الخروج من البرنامج؟',
    "noTitle": "بدون عنوان",
    "homePage": "الصفحة الرئيسية",
    "notificationPage": "صفحة الاشعارات",
    "favoritesPage": "المفضلة",
    "termsAndConditions": "الشروط والأحكام",
    "privacyPolicy": "سياسة الخصوصية",
    "invitefriend": "دعوة صديق",
    "all": "الكل",
    "nearest": "الاقرب",
    "distance": "المسافة",
    "noLocation": "خدمة التتبع مغلقة",
    "errorImage": "الصورة غير متوفرة",
    "inActive": "غير متاح",
    "active": "متاح",
    "address": "العنوان",
    "price": "السعر",
    "discount": "الخصم",
    "category": "التصنيف",
    "store": "المتجر",
    "status": "الحالة",
    "removeFavorite": "ازالة من المفضلة",
    "addFavorite": "اضافة الى المفضلة",
    "goToMap": "انتقل الى الخريطة",
    "priceAfterDiscount": "السعر بعد الخصم",
    "noData": "لا يوجد بيانات",
    "offers": "العروض",
    "markets": "المتاجر",
    "confirm": "تاكيد",
    'warning1': "هل انت متاكد من حذف كامل المفضلة؟"
  };
}
