class EnUs {
  static const Map<String, String> message = {
    "appName": "smart Shopping",
    'warning': 'warning',
    'yes': 'yes',
    'cancel': 'cancel',
    'alertexitingApp': 'are you sure of exiting app?',
    "noTitle": "No Title",
    "homePage": "Home Page",
    "notificationPage": "Notifications",
    "favoritesPage": "Favorites",
    "termsAndConditions": "Terms & Conditions",
    "privacyPolicy": "Privacy Policy",
    "invitefriend": "Invite A Friend",
    "all": "all",
    "nearest": "Nearest",
    "distance": "Distance",
    "noLocation": "tracking service is off",
    "errorImage": "Image not available",
    "inActive": "In Active",
    "active": "Active",
    "address": "Address",
    "price": "Price",
    "discount": "Discount",
    "category": "Category",
    "store": "Store",
    "status": "Status",
    "removeFavorite": "Remove from favorite",
    "addFavorite": "Add to favorite",
    "goToMap": "Go To Map",
    "priceAfterDiscount": "Price After Discount",
    "noData": "No Data",
    "offers": "Offers",
    "markets": "Markets",
    "confirm": "Confirm",

    //
    'warning1': "Are you sure of clearing all favorites?",
  };
}
